# Generated by Django 3.2 on 2023-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_title_page_pagetitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='articleTitle',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='article',
            new_name='articleTitleforPage',
        ),
    ]
